import { writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { DockerClient } from "@mecha/docker";
import { inspectContainer } from "@mecha/docker";
import { containerName, DEFAULTS, LABELS, MOUNT_PATHS, SECURITY } from "@mecha/core";
import type { MechaId } from "@mecha/core";
import {
  MechaEjectInput,
  EjectFileExistsError,
} from "@mecha/contracts";
import type { MechaEjectInputType, MechaEjectResultType } from "@mecha/contracts";
import { extractContainerOpts, readEnvValue } from "./helpers.js";

/** Env var keys that contain secrets — go in .env file, referenced as ${VAR} in compose */
const SECRET_KEYS = new Set([
  "MECHA_AUTH_TOKEN",
  "CLAUDE_CODE_OAUTH_TOKEN",
  "ANTHROPIC_API_KEY",
  "MECHA_OTP",
]);

/** Env var keys managed internally — inline in compose environment section */
const INTERNAL_KEYS = new Set([
  "MECHA_ID",
  "MECHA_PERMISSION_MODE",
  "MECHA_DB_PATH",
]);

/** Keys to exclude entirely from output (set by Docker/OS, not user-relevant) */
const EXCLUDED_KEYS = new Set([
  "PATH", "HOME", "USER", "SHELL",
  "LD_PRELOAD", "LD_LIBRARY_PATH",
]);

export async function mechaEject(
  client: DockerClient,
  input: MechaEjectInputType,
): Promise<MechaEjectResultType> {
  const parsed = MechaEjectInput.parse(input);
  const { id, force } = parsed;
  const mechaId = id as MechaId;
  const cName = containerName(mechaId);

  const info = await inspectContainer(client, cName);
  const opts = extractContainerOpts(info, cName, mechaId);
  const allEnv = (info.Config?.Env ?? []) as string[];

  // Classify env vars
  const secretEnv: Array<{ key: string; value: string }> = [];
  const inlineEnv: Array<{ key: string; value: string }> = [];
  const userEnv: Array<{ key: string; value: string }> = [];

  for (const entry of allEnv) {
    const eqIdx = entry.indexOf("=");
    if (eqIdx <= 0) continue;
    const key = entry.slice(0, eqIdx);
    const value = entry.slice(eqIdx + 1);
    if (EXCLUDED_KEYS.has(key)) continue;
    if (SECRET_KEYS.has(key)) {
      secretEnv.push({ key, value });
    } else if (INTERNAL_KEYS.has(key)) {
      inlineEnv.push({ key, value });
    } else {
      userEnv.push({ key, value });
    }
  }

  // Build environment section for compose
  const envLines: string[] = [];
  for (const { key, value } of inlineEnv) {
    envLines.push(`      ${key}: "${value}"`);
  }
  for (const { key } of secretEnv) {
    envLines.push(`      ${key}: "\${${key}}"`);
  }
  for (const { key, value } of userEnv) {
    envLines.push(`      ${key}: "${value}"`);
  }

  // Build .env content
  const dotEnvLines: string[] = [
    `# Generated by: mecha eject ${id}`,
    `# Secret environment variables for docker compose`,
  ];
  for (const { key, value } of secretEnv) {
    dotEnvLines.push(`${key}=${value}`);
  }

  // Build ports section
  const portLine = opts.hostPort
    ? `\n    ports:\n      - "127.0.0.1:${opts.hostPort}:${DEFAULTS.CONTAINER_PORT}"`
    : "";

  // Build compose YAML
  const compose = `# Generated by: mecha eject ${id}
# Manage with: docker compose up -d / docker compose down
services:
  mecha:
    image: ${opts.image}
    container_name: ${cName}
    environment:
${envLines.join("\n")}
    labels:
      ${LABELS.IS_MECHA}: "true"
      ${LABELS.MECHA_ID}: "${mechaId}"
      ${LABELS.MECHA_PATH}: "${opts.projectPath}"
    networks:
      - ${DEFAULTS.NETWORK}${portLine}
    volumes:
      - type: bind
        source: .
        target: ${MOUNT_PATHS.WORKSPACE}
      - ${opts.volumeName}:${MOUNT_PATHS.STATE}
    tmpfs:
      - ${MOUNT_PATHS.TMP}:rw,noexec,nosuid,size=256m
    security_opt:
      - ${SECURITY.SECURITY_OPT[0]}
    cap_drop:
      - ${SECURITY.CAP_DROP[0]}
    read_only: true
    user: "${SECURITY.UID}:${SECURITY.GID}"

volumes:
  ${opts.volumeName}:
    external: true

networks:
  ${DEFAULTS.NETWORK}:
    external: true
`;

  // Resolve output path
  const projectPath = opts.projectPath;
  const composePath = join(projectPath, "docker-compose.yml");
  const envPath = join(projectPath, ".env");

  // Check for existing files
  if (!force) {
    if (existsSync(composePath)) throw new EjectFileExistsError(composePath);
    if (existsSync(envPath)) throw new EjectFileExistsError(envPath);
  }

  // Write files
  await writeFile(composePath, compose, "utf-8");
  await writeFile(envPath, dotEnvLines.join("\n") + "\n", "utf-8");

  return { id, composePath, envPath };
}
